[package]
name = "pwgen"
version = "0.1.0"
authors = ["mizusashi <sakdfjidoie@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = {version = "0.7.3"}
